// Generated by Selenium IDE
using System;// importer la bibliothèque system
using System.Net.Mail;
using System.Threading.Tasks;
using NUnit.Framework;// importer la bibliothèque NUnit
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using TestESG;


namespace TestESG // regrouper des classes
{
    [TestFixture] //attribut de classe, il sert à détecter les classes de test (lier au framwork de test)
    public class TestsAU // public a pour objectif de rendre la classe accessible partout dans le projet de test.
    {

        public IWebDriver driver;
        IJavaScriptExecutor js;
        ReadData Read = new ReadData();
        Client client;


        [SetUp] //définir la méthode SetUp(),afin qu'elle soit exécutée avant la méthode test
        public void Setup()//prérequis de la méthode de test
        {
            driver = new ChromeDriver(@"C:\\Users\\Bouss\\SELENIUM\\chromedriver.exe");
            Console.WriteLine("je suis dans la methode setup");// affichage 
        }

        [Test]//définir la méthode de test, executée apres la methode setup()
        public void Test()//méthode de test (actions,vérifications, paramètres(conditions,variables)  )
        {

            client = Read.ReadDataFromJson();

            Console.WriteLine("je suis dans la methode TEST");// affichage 
            driver.Navigate().GoToUrl("https://souscription.cetelem.fr/fr/souscription/identite?subscriptionuuid=7356ddcd-9488-4184-90d0-efed3faee752&co=LDEFOD");

            // Pause fixe de 3 secondes pour permettre à la page de se charger
            //Thread.Sleep(3000);

            driver.FindElement(By.XPath("//*[@id=\"onetrust-accept-btn-handler\"]")).Click();
            Assert.AreEqual("Faisons connaissance", driver.FindElement(By.XPath("//*[@id=\"identite-title\"]")).Text);

            //IWebElement element = driver.FindElement(By.Id("rippleContainer"));// 
            //js = (IJavaScriptExecutor)driver;
            //js.ExecuteScript("arguments[0].scrollIntoView(true);", element);


            driver.FindElement(By.XPath("//*[@id=\"input\"]")).SendKeys(client.FirstName);
            driver.FindElement(By.XPath("//*[@id=\"input\"]")).SendKeys(client.LastName);
            SelectElement select = new SelectElement(driver.FindElement(By.XPath("//*[@id=\"root\"]/div/div[2]/div[2]/div/div/gender-input[1]/selected-button[1]")));
            select.SelectByValue("Mr");



            driver.FindElement(By.XPath("//*[@id=\"edit-submitted-email\"]")).SendKeys(client.EmailAddress);
            driver.FindElement(By.XPath("//*[@id=\"edit-submitted-telephone\"]")).SendKeys(client.PhoneNumber);
            driver.FindElement(By.XPath("//*[@id=\"edit-submitted-rgpd\"]/div/label")).Click();
            
            IWebElement element2 = driver.FindElement(By.XPath("//*[@id=\"webform-client-form-4653\"]/div/div[8]/input"));// 
            //javascript
            js = (IJavaScriptExecutor)driver;
            js.ExecuteScript("arguments[0].scrollIntoView(true);", element2);
            driver.FindElement(By.XPath("//*[@id=\"webform-client-form-4653\"]/div/div[8]/input")).Click();

            driver.FindElement(By.Id("input_2")).Submit();

            Assert.AreEqual("Thank You!", driver.FindElement(By.XPath("//*[@id=\"stage\"]/div[1]/div/div/h1")).Text);

        }

        [TearDown]//définir la méthode TearDown(),afin qu'elle soit exécutée après la méthode testMethod.
        public void TearDown()//la méthode TearDown exécutée en dernier (fermeture de navigateur)
        {
            Console.WriteLine("je suis dans la methode TearDown");// affichage
            //driver.Close();
            //newdriver.Quit();

        }

    }
}
