// Generated by Selenium IDE
using System;// importer la bibliothèque system
using System.Net.Mail;
using System.Threading.Tasks;
using NUnit.Framework;// importer la bibliothèque NUnit
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using TestESG;


namespace TestESG // regrouper des classes
{
    [TestFixture] //attribut de classe, il sert à détecter les classes de test (lier au framwork de test)
    public class Tests // public a pour objectif de rendre la classe accessible partout dans le projet de test.
    {

        public IWebDriver newdriver;
        IJavaScriptExecutor js;
        ReadData Read = new ReadData();
        Client client;


        [SetUp] //définir la méthode SetUp(),afin qu'elle soit exécutée avant la méthode test
        public void Setup()//prérequis de la méthode de test
        {
            newdriver = new ChromeDriver(@"C:\\Users\\Bouss\\SELENIUM\\chromedriver.exe");
            Console.WriteLine("je suis dans la methode setup");// affichage 
        }

        [Test]//définir la méthode de test, executée apres la methode setup()
        public void Test()//méthode de test (actions,vérifications, paramètres(conditions,variables)  )
        {
            
            client = Read.ReadDataFromJson();

            Console.WriteLine("je suis dans la methode TEST");// affichage 
            newdriver.Navigate().GoToUrl("https://form.esg-sport.com/candidature-ligne");

            // Pause fixe de 3 secondes pour permettre à la page de se charger
            //Thread.Sleep(3000);

            newdriver.FindElement(By.Id("onetrust-accept-btn-handler")).Click();
            Assert.AreEqual("CRÉATION DU COMPTE CANDIDAT", newdriver.FindElement(By.XPath("//*[@id=\"content\"]/article/div/div[2]/div/h1")).Text);

            newdriver.FindElement(By.Id("edit-submitted-first-name")).SendKeys(client.FirstName);
            newdriver.FindElement(By.Id("edit-submitted-last-name")).SendKeys(client.LastName);
            newdriver.FindElement(By.XPath("//*[@id=\"edit-submitted-email\"]")).SendKeys(client.EmailAddress);
            newdriver.FindElement(By.XPath("//*[@id=\"edit-submitted-telephone\"]")).SendKeys(client.PhoneNumber);
            newdriver.FindElement(By.XPath("//*[@id=\"edit-submitted-rgpd\"]/div/label")).Click();
            IWebElement element = newdriver.FindElement(By.XPath("//*[@id=\"webform-client-form-4653\"]/div/div[8]/input"));// 
            //javascript
            js = (IJavaScriptExecutor)newdriver;
            js.ExecuteScript("arguments[0].scrollIntoView(true);", element);
            newdriver.FindElement(By.XPath("//*[@id=\"webform-client-form-4653\"]/div/div[8]/input")).Click();

            newdriver.FindElement(By.Id("input_2")).Submit();

            Assert.AreEqual("Thank You!", newdriver.FindElement(By.XPath("//*[@id=\"stage\"]/div[1]/div/div/h1")).Text);

        }

        [TearDown]//définir la méthode TearDown(),afin qu'elle soit exécutée après la méthode testMethod.
        public void TearDown()//la méthode TearDown exécutée en dernier (fermeture de navigateur)
        {
            Console.WriteLine("je suis dans la methode TearDown");// affichage
            //driver.Close();
            //newdriver.Quit();

        }

    }
}
